spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://localhost:8090/realms/master}
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: cash-service
            client-secret: ${CLIENT_SECRET:I0StlCY5tNJTvaIbPJdiMBgGtmIR5yN1}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8090/realms/master}

server:
  port: 8030

service:
  account:
    url: lb://gateway-service/account
  blocker:
    url: lb://gateway-service/blocker
  notifications:
    url: lb://gateway-service/notification