spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      mvc:
        routes:
          - id: account-service
            uri: ${cloud.account-service-url}
            predicates:
              - Path=/account/**
            filters:
              - RewritePath=/account/?(?<segment>.*), /$\{segment}
          - id: cash-service
            uri: ${cloud.cash-service-url}
            predicates:
              - Path=/cash/**
            filters:
              - RewritePath=/cash/?(?<segment>.*), /$\{segment}
          - id: transfer-service
            uri: ${cloud.transfer-service-url}
            predicates:
              - Path=/transfer/**
            filters:
              - RewritePath=/transfer/?(?<segment>.*), /$\{segment}
          - id: exchange-service
            uri: ${cloud.exchange-service-url}
            predicates:
              - Path=/exchange/**
            filters:
              - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
          - id: exchange-generator-service
            uri: ${cloud.exchange-generator-service-url}
            predicates:
              - Path=/exchange-generator/**
            filters:
              - RewritePath=/exchange-generator/?(?<segment>.*), /$\{segment}
          - id: blocker-generator
            uri: ${cloud.blocker-service-url}
            predicates:
              - Path=/blocker/**
            filters:
              - RewritePath=/blocker/?(?<segment>.*), /$\{segment}
          - id: notification-service
            uri: ${cloud.notification-service-url}
            predicates:
              - Path=/notification/**
            filters:
              - RewritePath=/notification/?(?<segment>.*), /$\{segment}
server:
  port: 8200

cloud:
  account-service-url: lb://account-service
  cash-service-url: lb://cash-service
  transfer-service-url: lb://transfer-service
  exchange-service-url: lb://exchange-service
  exchange-generator-service-url: lb://exchange-generator-service
  blocker-service-url: lb://blocker-service
  notification-service-url: lb://notification-service