apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: {{ .Values.secrets.keycloak.clientId | b64enc }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloak.clientSecret | b64enc }}