apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: k8s
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
  SPRING_JPA_DATABASE: postgresql
  SPRING_JPA_HIBERNATE_DDL-AUTO: validate
  SPRING_JPA_SHOW-SQL: "true"
  SERVER_PORT: "{{ .Values.service.port }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "{{ .Values.global.services.keycloak.url }}"
