apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account-service.fullname" . }}-db
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.database.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.database.password | b64enc }}
  SPRING_DATASOURCE_URL: {{ .Values.secrets.database.url | b64enc }}