apiVersion: v2
name: account-service
description: Helm chart for the Account microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "16.7.10"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: account-postgres
    condition: account-postgres.enabled