replicaCount: 1

image:
  repository: account-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 80

account-postgres:
  enabled: true
  auth:
    database: account
    username: postgres
    password: "postgres"
  primary:
    persistence:
      enabled: true
      size: 1Gi

secrets:
  database:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://bankapp-account-postgres:5432/account"