replicaCount: 1

image:
  repository: front-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 80

secrets:
  keycloak:
    clientId: "front-service"
    clientSecret: "eTI5yoY93m9nZj2FRDRKSyIxocTEfAaO"