replicaCount: 1

image:
  repository: transfer-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 80

secrets:
  keycloak:
    clientId: "transfer-service"
    clientSecret: "5CW9tuhQgl3mIMKvYarcOn8JRt4g8fGF"