replicaCount: 1

image:
  repository: exchange-generator-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 80

secrets:
  keycloak:
    clientId: "exchange-generator-service"
    clientSecret: "WWjquJ7Uz2owLuo0v6Ptibn2jZ288B80"