--liquibase formatted sql

--changeset azmeev:1
CREATE TABLE BANK_EXCHANGE_RATES (
    ID bigint not null primary key generated by default as identity,
    CURRENCY varchar(256) not null,
    VALUE numeric not null
);