apiVersion: v2
name: exchange-service
description: Helm chart for the Exchange microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "16.7.10"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: exchange-postgres
    condition: exchange-postgres.enabled