--liquibase formatted sql

--changeset azmeev:1
CREATE TABLE BANK_USERS (
    ID bigint not null primary key generated by default as identity,
    LOGIN varchar(256) not null,
    PASSWORD text not null,
    NAME varchar(256) not null,
    BIRTHDATE date not null
);